language: ruby
bundler_args: --without development
rvm:
  - 1.9.2
  - 1.9.3
  
before_script:
  - psql -c 'create database rails_reverse_db_test;' -U postgres
  - mysql -e 'create database rails_reverse_db_test;'
  
gemfile:
  - gemfiles/rails3_0.gemfile
  - gemfiles/rails3_1.gemfile
  - gemfiles/rails3_2.gemfile