development:
  adapter: mysql2
  database: rails_reverse_db_dev
  username: root
  password: root

test:
  adapter: mysql2
  database: rails_reverse_db_test
  username: root
  encoding: utf8
  
test_pg:
  adapter: postgresql
  database: rails_reverse_db_test
  username: postgres

production:
  adapter: mysql2
  database: rails_reverse_db
  username: root
  password: root
